class DriveManager:
    def __init__(self, crap):
        ...

    def exists(self, file: str) -> bool:
        ...

    def read(self, file: str) -> str:
        ...

    def create(self, filename: str) -> None:
        ...

    def write(self, file_name: str, file_contents: str) -> None:
        ...